# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog
name: MACHINE MEMOS
email: info@machinememos.com
location: Nuremberg, Germany # ex. Nice, France
company: 
company_url: machinememos.com
github_url: https://github.com/n-kostadinov # ex. https://github.com/DONGChuan
description: Love to AI.
favicon: favicon.png # Image must be in assets/images
repository: n-kostadinov/n-kostadinov.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://machinememos.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

# Disque
disque: machinememos-com

# Pagination
paginate: 50
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: BLOG

  -
    href: /code
    label: CODE

  -
    href: /timeline
    label: TIMELINE

  -
    href: /about
    label: ABOUT

# Sidebar to show popular repo
side_bar_repo_limit: 999 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'UA-26182347-1'  # ex. UA-72165600-X
